name: Build and Deploy Github Pages

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.8.0]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install -g @angular/cli
          npm ci
          ng deploy --repo=https://github.com/IashuraI/portfolio.git --message="Built from ${GITHUB_SHA} in the source repository." --branch=master
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GithubToken }}
          EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
